// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class StockItem
    {
        public StockItem()
        {
            StockAccessory = new HashSet<StockAccessory>();
            StockImage = new HashSet<StockImage>();
        }

        public int StockItemId { get; set; }
        public string RegNo { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string ModelYear { get; set; }
        public string Kms { get; set; }
        public string Colour { get; set; }
        public string Vin { get; set; }
        public decimal? RetailPrice { get; set; }
        public decimal? CostPrice { get; set; }
        public DateTime? Dtcreated { get; set; }
        public DateTime? Dtupdated { get; set; }

        public virtual ICollection<StockAccessory> StockAccessory { get; set; }
        public virtual ICollection<StockImage> StockImage { get; set; }
    }
}